name: base
channels:
  - defaults
  - rdkit
  - conda-forge
  - pytorch
dependencies:
  - conda
  - python=3.7
  - pytorch
  - nb_conda_kernels
  - seaborn
  - rdkit
  - jupyter
  - ipywidgets
  - tqdm
  - yapf
  - cudatoolkit=10.1
  - torchvision
  - jupyter_contrib_nbextensions
  - numpy
  - dask
  - matplotlib
  - scipy
  - isort
  - scikit-learn

